CREATE TABLE IF NOT EXISTS dates (
id VARCHAR NOT NULL,
name VARCHAR NOT NULL,
count_ INT NOT NULL,
day TIMESTAMP,
status enum("SUGGESTED", "JOINTAPPROVED", "REJECTED") NOT NULL,
description VARCHAR, 
PRIMARY KEY(id)
);

