name: Rust

on:
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yml"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: SQLX
        run: cargo install sqlx-cli --no-default-features --features native-tls,postgres
      - name: SQLX migrate
        run: cargo sqlx migrate run
      - name: Build
        run: |
          export DATABASE_URL=postgres://postgres:assword@localhost:5432/postgres
          cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
